name: Build & Test
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - name: Build multi-arch
        run: |
          GOOS=windows GOARCH=amd64 go build -o snyk-history-scanner.exe
          GOOS=darwin GOARCH=amd64 go build -o snyk-history-scanner-darwin
          GOOS=linux GOARCH=amd64 go build -o snyk-history-scanner-linux
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - name: Build multi-arch
        run: |
          go test ./...